### ISSUE TITLE
função hideAppBar não está funcionando

### ISSUE THREAD

**Issue by izacximenes** [stone-payments/pos-mamba-sdk#467]
Estou usando a função this.root.meta.hideAppBar(boolean) para esconder o appBar, mas não está acontecendo nada

**Comment by steinjonathan** [comment]
> Estou usando a função this.root.meta.hideAppBar(boolean) para esconder o appBar, mas não está acontecendo nada

Jovem, defina  _hideAppBar=true na declaração da AppBar.
