### ISSUE TITLE
Função Payment.cancel(atk) não está funcionando

### ISSUE THREAD

**Issue by leoseefeld** [stone-payments/pos-mamba-sdk#476]
Ao utilizar a função de cancelamento com o atk o sistema apenas abre o app de cancelamento e não limita o cancelamento ao atk especificado.

**Comment by didiraja** [comment]
Esta demanda, entrou recentemente em nosso backlog. 

Para mais contatos, fale conosco através do [Slack](http://stone-mambaweb.slack.com)
