### ISSUE TITLE
Falha na impressão de conteúdo extenso

### ISSUE THREAD

**Issue by leoseefeld** [stone-payments/pos-mamba-sdk#477]
Ao imprimir utilizando o componente Printable nos casos em que o conteúdo é extenso a impressão pause por alguns milissegundos, retoma com maior rapidez e para antes do final do conteúdo.

**Comment by didiraja** [comment]
@leoseefeld procure-nos em [nosso canal do Slack](http://stone-mambaweb.slack.com), para que possamos te ajudar.
